version: "3.6"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
